[build-system]
requires = ["scikit-build-core>=0.10", "cython>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "bitbuf"
version = "0.3.0-beta.0"
description = "A fast and lightweight bit-level mutation library for Python."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "Anthony Donlon" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[project.optional-dependencies]
test = [
  "pytest",
  "setuptools",
]

[tool.scikit-build]
minimum-version = "0.10"
build-dir = "build/{wheel_tag}"

[tool.scikit-build.wheel]
packages = ["bitbuf"]

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
testpaths = ["tests"]
pythonpath = ["."]

[tool.cibuildwheel]
build = "cp3*-*"
skip = ["pp*", "*musllinux*"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
ignore = [
  'E722', # Bare-except
]

[tool.ruff.format]
