from __future__ import annotations

from typing import TypeAlias

InputTypes: TypeAlias = int | bytes | bytearray | memoryview | bitbuf

class bitbuf:
    def __init__(self, value: InputTypes = 0, width: int | None = None) -> None: ...

    @classmethod
    def zeros(cls, width: int) -> bitbuf: ...
    @classmethod
    def ones(cls, width: int) -> bitbuf: ...

    def __eq__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: int | slice) -> int: ...
    def __setitem__(self, key: int | slice, value: InputTypes) -> None: ...
    def __iadd__(self, value: bytes | bytearray | bitbuf) -> bitbuf: ...
    def __ilshift__(self, bits: int) -> bitbuf: ...
    def __irshift__(self, bits: int) -> bitbuf: ...

    def assign(self, value: InputTypes = 0, width: int | None = None) -> bitbuf: ...
    def resize(self, width: int) -> bitbuf: ...
    def clone(self) -> bitbuf: ...
    def clear(self) -> bitbuf: ...

    def get_bit(self, pos: int) -> int: ...
    def get_bits(self, pos: int, width: int) -> int: ...
    def get_bits_as_bytes(self, pos: int, width: int) -> bytes: ...
    def get_bits_as_bytearray(self, pos: int, width: int) -> bytearray: ...
    def slice(self, pos: int, width: int) -> bitbuf: ...

    def clear_bit(self, pos: int) -> bitbuf: ...
    def set_bit(self, pos: int, value: int = 1) -> bitbuf: ...
    def set_bits(self, pos: int, value: InputTypes = 0, width: int | None = None) -> bitbuf: ...
    def set_ones(self, pos: int, width: int) -> bitbuf: ...
    def set_zeros(self, pos: int, width: int) -> bitbuf: ...
    def toggle(self, pos: int = 0, width: int | None = None) -> bitbuf: ...

    def lshift(self, bits: int) -> bitbuf: ...
    def rshift(self, bits: int) -> bitbuf: ...

    def append_low(self, value: InputTypes = 0, width: int | None = None) -> bitbuf: ...
    def append_high(self, value: InputTypes = 0, width: int | None = None) -> bitbuf: ...
    def delete_low(self, width: int) -> bitbuf: ...
    def delete_high(self, width: int) -> bitbuf: ...
    def pop_low(self, width: int) -> int: ...
    def pop_high(self, width: int) -> int: ...

    def bytearray(self) -> bytearray: ...
    def bytes(self) -> bytes: ...
    def hex(self) -> str: ...
    def int(self) -> int: ...

    @property
    def width(self) -> int: ...

    @property
    def nbytes(self) -> int: ...

    @property
    def _offset(self) -> int: ...
