from __future__ import annotations

from typing import TypeAlias

InputTypes: TypeAlias = int | bytes | bytearray | memoryview | bitbuf

class bitbuf:
    def __init__(self, value: InputTypes = 0, length: int | None = None): ...

    @classmethod
    def zeros(cls, length: int) -> bitbuf: ...
    @classmethod
    def ones(cls, length: int) -> bitbuf: ...
    @classmethod
    def from_buffer(cls, buffer: InputTypes, pos: int, length: int) -> bitbuf: ...
    @classmethod
    def random(cls, length: int) -> bitbuf: ...

    def __eq__(self, other: bitbuf) -> bool: ...
    def __len__(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: int | slice) -> int: ...
    def __setitem__(self, key: int | slice, value: InputTypes): ...
    def __iadd__(self, value: bytes | bytearray | bitbuf) -> bitbuf: ...
    def __ilshift__(self, bits: int) -> bitbuf: ...
    def __irshift__(self, bits: int) -> bitbuf: ...

    def assign(self, value: InputTypes = 0, length: int = -1): ...
    def resize(self, length: int): ...
    def clone(self) -> bitbuf: ...
    def clear(self): ...

    def get_bit(self, pos: int) -> int: ...
    def get_bits(self, pos: int, length: int) -> int: ...
    def get_bits_as_bytes(self, pos: int, length: int) -> bytes: ...
    def get_bits_as_bytearray(self, pos: int, length: int) -> bytearray: ...
    def slice(self, pos: int, length: int) -> bitbuf: ...

    def clear_bit(self, pos: int): ...
    def set_bit(self, pos: int, value: int = 1): ...
    def set_bits(self, pos: int, value: InputTypes, length: int = -1): ...
    def set_ones(self, pos: int, length: int): ...
    def set_zeros(self, pos: int, length: int): ...
    def toggle(self, pos: int = -1, length: int = -1): ...

    def lshift(self, bits: int): ...
    def rshift(self, bits: int): ...

    def append_low(self, value: InputTypes, length: int = -1): ...
    def append_high(self, value: InputTypes, length: int = -1): ...
    def delete_low(self, length: int): ...
    def delete_high(self, length: int): ...
    def pop_low(self, length: int) -> int: ...
    def pop_high(self, length: int) -> int: ...

    def bytearray(self) -> bytearray: ...
    def bytes(self) -> bytes: ...
    def hex(self) -> str: ...
    def int(self) -> int: ...

    @property
    def length(self) -> int: ...

    @property
    def nbytes(self) -> int: ...

    @property
    def offset(self) -> int: ...


_ABI_VERSION: int
# """Get Cython module ABI version."""
